### ISSUE TITLE
Still maintained? errors

### ISSUE THREAD

**Issue by sebastienbarre** [twardoch/remark-mark-plus#6]
Hello

I was just wondering if this package was still maintained?

I was trying to use it from MDX, and got the following errors:
```
Cannot read properties of undefined (reading 'inlineTokenizers')
```

I cloned the repo, tried to run the tests, to no avail unfortunately:
```
npm run test  

> remark-mark-plus@1.0.21 test
> jest

 FAIL  __tests__/index.js
  ● Test suite failed to run

    TypeError: /Users/sebastien.barre/Development/Src/playground/remark-mark-plus/__tests__/index.js: Cannot read properties of null (reading 'bindings')

      at Scope.moveBindingTo (node_modules/@babel/traverse/lib/scope/index.js:993:13)
      at BlockScoping.updateScopeInfo (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
      at BlockScoping.run (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
      at PluginPass.BlockStatementSwitchStatementProgram (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:177:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:100:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:103:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:77:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.26 s
```

Thank you

**Comment by twardoch** [comment]
I hacked it together based on some existing models but I'm not really much of a JS dev. It used to work but I haven't used it much recently.

**Comment by sebastienbarre** [comment]
Thank you

**Comment by talatkuyuk** [comment]
I receive the same error. **Is there anybody to handle this plugin in operational?** I will really appreciate him/her.
